name: Ricky and Monty Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 8 * * *'  # Runs at 8 AM UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cypress
        uses: cypress-io/github-action@v7
        with:
          cypress-version: ^12.0.0
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v7
        with:
          start: npx cypress run 
      - name: Send Email with Cypress Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject:  Test Report
          to: orji@outlook.com
          from: aso@gmail.com
          body: "Please find attached daily scheduled test report."
          content_type: text/html
          attachments: index.html
      
    